### ISSUE TITLE
Wrong default permissions of /shared_data/accounting.txt in acl labtainer

### ISSUE THREAD

**Issue by nikifor** [mfthomps/Labtainers#11]
On page 2 of the acl lab description, the guide claims that accounting.txt must have the following permissions:

-rw-rw----+ 

The file however seems to have the following permissions by default:
-rw-rw-r--+

Which kind of invalidates the reason why Bob would want Alice to run his trojan program.

**Comment by mfthomps** [comment]
Thank you.  The permissions have been fixed.  You'll need to run:
   removelab.py acl
and then rerun the lab to see the change.

**Comment by nikifor** [comment]
Great, thank you!
