### ISSUE TITLE
install labtainer

### ISSUE THREAD

**Issue by alaagalal** [mfthomps/Labtainers#12]
I am new in Linux and i find some difficult in installing the labtainer 
first how can i run any in labtainer 
after making anew directory for new lab and named it ,then i must install new_lab_setup.py
i can't do this step
i need some help 
thanks in advance

**Comment by mfthomps** [comment]
Are you trying to run existing labs, or create a new lab exercise?  To run existing Labtainer labs, please see the Student guide at: https://my.nps.edu/documents/107523844/109121513/labtainer-student.pdf
To run existing labs, there is no separate installation step and no need to run new_lab_setup.py

If you are creating a new lab, follow the steps in https://my.nps.edu/documents/107523844/109121513/labdesigner.pdf section 3.1
Before creating new labs, consider running existing labs and reviewing their construction.

**Comment by alaagalal** [comment]
According to the pdf to start any lab 
i must be in  the location of labtainer_student 
then 
start.py <labname>
where labname is the name of the lab to run

I can't recognize the names of labs 
I just found 3 directories called bin  ,  lab_bin and lab_sys
Thanks in advance

**Comment by alaagalal** [comment]
how can i login to any lab
?

**Comment by alaagalal** [comment]
how can i login the lab ?
how can i get surname and password to get the the verification?

**Comment by mfthomps** [comment]
While in the labtainer-student directory try:
labtainer nix-commands
as an example.   Do not confuse yourself about the subdirectories, they are not relevant to  your question.  And do not bother with labtainer-instructor -- that is used by instructors to grade labs.
I do not understand your question about logging into the lab.  The VM username is "student" and the password is "password123".

**Comment by alaagalal** [comment]
> While in the labtainer-student directory, type "labtainer" to see a list of labs. Then type
> "labtainer "
> giving the name of the lab you want to run.

labtainer student directory has only two direcories called bin and lab_bin ?
which one ?
and i run the lab that was found inlabtainer-instructor is it right ?
IF i closed the lab how can restart joining one more time the same lab?

**Comment by mfthomps** [comment]
After using "stoplab" to stop a lab, you can then restart it with the labtainer command.  Your previous work will remain.  If you wish to restart a lab from scratch, use the "-r" command.
