### ISSUE TITLE
Is the autograder for the "gdblesson" lab working?

### ISSUE THREAD

**Issue by nikifor** [mfthomps/Labtainers#13]
Hi,

I was just working through the lab called "gdblesson" and I am not sure that the autograder works as it should. I finished all the tasks described in that lab yet the autograder (which I guess is the same whether the student runs "checkwork" or the instructor runs "gradelab") only credited me for half of them.

I was credited with having done the following correctly:
gdb_run_task, gdb_list_task, gdb_print_task, gdb_step_task

and none of the remaining ones. This is particularly surprising given that I could not have used gdb without successfully using gcc first, yet I am not credited with the gcc_task_one task.

Would you mind verifying that the autograder works?

**Comment by mfthomps** [comment]
Hi Nick,
I've fixed the grading for that gdblession lab.  Run "update-labtainer.sh"
to get the fixes.  That lab was built by a summer intern, and I should have
done more to QA it at the time.  The grading for that lab could use
additional attention, e.g., to tell the instructor what is being assessed.
But it is now functional.
Thanks,
--Mike
