### ISSUE TITLE
Checkwork/Gradelab/Redo bug

### ISSUE THREAD

**Issue by xigaoli** [mfthomps/Labtainers#14]
Hi,

There's a bug on "labtainer --redo", "checkwork" and "gradelab".
 - Bug:
   1. While a user using the labtainer --redo <labname> to redo the lab, the old results did not get cleared and may affect new results (see 2).

   2. If one deleted the zip file in labtainer_xfer, using checkwork will continue to show the previous results and save previous results into labtainer_xfer.

 - Reason:

    This is because the zip file is also stored into /var/lib/docker/overlay2/\<id\>/merged/home/instructor/, where is inaccessible by "student" account (need superuser access). Those files are not deleted even using labtainer --redo option, and will still be gradable by checkwork and gradelab.

 - Solution:
    1. find those zip files using the find command (replace the onewayhash to your lab name):
**$ sudo find /\* | grep .onewayhash.zip**
    2. it will get something like this:
/var/lib/docker/overlay2/cd5f35bb65cf3161d60b5eba7c12753484f7c38f689ebd71c6173d1027d3e10d/merged/home/instructor/(e-mail).onewayhash.zip
or 
/var/lib/docker/overlay2/cd5f35bb65cf3161d60b5eba7c12753484f7c38f689ebd71c6173d1027d3e10d/diff/home/instructor/(e-mail).onewayhash.zip 
or both.
    3. delete those files
**$sudo rm <filepath.zip>**
    4. run checkwork <labname>, if everything is good, checkwork will show no results; now you can start a clean lab work.
--if checkwork still shows previous lab result, you can do 1-4 again (I forget to delete one of it once and its coming back.)

However its only a temp solution, hope this can be resolved.

**Comment by mfthomps** [comment]
Hi,
Thank for the report.  I'll dig into it further, but would like to solicit opinions about the desired behavior of --redo when issued by the student.  The original intent was to simply allow the student to get a fresh container that is free of any artifacts from previous work to allow performance of the lab without effects due to previous work.  It was not intended to erase the history of the previous work, nor eliminate artifacts related to performance.   For example, you do the lab, get it right and then decide you want to try some crazy stuff on the lab.  So you use --redo and experiment and explore.  Then you submit your work to the instructor.  Shouldn't you get credit for getting it right, even though you later tried some experiments?

Perhaps Labtainers needs a distinct command to "hide my previous work from the world". I'd expect that deleting the zip and then doing a --redo would achieve that, but am only guessing for now.
Again, I'll dig into it some more, having forgotten much of what the current implementation does about the zip files in the --redo flag.  Any thoughts on desired behavior are appreciated.  Thanks again.

**Comment by xigaoli** [comment]
Hi Mike,

Thanks a lot!

Indeed, labtainer may need a command to erase the previous work.
What I met today is a student did part of the work, then he used --redo and want a fresh start; however the labtainer preserved (and reverted) his previous work when he using the checkwork command.

Another example is when I grading the lab using gradelab, I graded some students (A), and then want to grade some new student submissions (B) so I deleted the (A), but gradelab will still show the grade (A), mixed with (B). And if I want to do the lab myself, I can't get rid of the students' results - they are permanent if not "find then sudo rm" them.

Sometimes labtainer labs runs into trouble such as work counter not increasing, checkwork not showing satisfied result, etc, students want to do it from a clean start, so using checkwork showing previous results make them confusing.

For the --redo command, (correct me if I'm wrong), if a user did something else in labtainer using --redo, should it show the corresponding results? Otherwise it also may confuse the user; for the original version of finished work, From my personal view, user can(should) preserve the original output (copy the zip from labtainer_xfer) to somewhere else by himself.

From a brief look at the redo (labutils.py:1973 - RedoLab() and StartLab()) python script, current implementation only starts a fresh container. Might be better if deletes all previously saved files (or get a new command doing this).

Really appreciated!

**Comment by mfthomps** [comment]
Next week I'll publish an update that changes the "checkwork" function so
that it always uses a fresh container.  That will allow a student to delete
content of the labtainer_xfer/<lab> directory then run with a --redo so as
to not have any remnant of past work appear in the future checkwork
operations.  In general we do not suggest that students delete from the
labtainer_xfer directory.  A central property of Labtainers is that
students need manage different copies of zip files and need not worry about
which results are turned in.  The model is that all results always get
turned in and you get credit if you ever achieved the goal.  To clarify,
the "checkwork" function was not reverting anything in the lab containers.
It was simply answering the question, did you ever achieve these goals?

More replies are in line with your message below:

On Fri, Mar 8, 2019 at 8:04 PM Xigao Li <notifications@github.com> wrote:

> Hi Mike,
>
> Thanks a lot!
>
> Indeed, labtainer may need a command to erase the previous work.
> What I met today is a student did part of the work, then he used --redo
> and want a fresh start; however the labtainer preserved (and reverted) his
> previous work when he using the checkwork command.
>
As noted above, previous work was not being reverted.  The checkwork
containers was simply keeping track of past work, even if the xfer
directory was delete.  The change I'm making will cause checkwork to use a
fresh container each time.

> Another example is when I grading the lab using gradelab, I graded some
> students (A), and then want to grade some new student submissions (B) so I
> deleted the (A), but gradelab will still show the grade (A), mixed with
> (B). And if I want to do the lab myself, I can't get rid of the students'
> results - they are permanent if not "find then sudo rm" them.
>
It does not seem you are using Labtainers as intended.  Collect all student
zip files into the xfer directory and run gradelab.  tt grades all of the
student work at the same time, and produces a separate report for each
student.  As long as students use distinct email addresses, their results
are separate.  If you do the lab yourself, your results are separate.  The
fact that you also see assessment of the student work has no bearing on the
assessment of your own work.   Each time you run gradelab -r, it gathers
fresh results from the xfer directory.  So, even if you insist on wanting
to delete artifacts (which is contrary to the intended use), you need only
delete from the xfer directory and then run gradelab -r.    There is no
need for "sudo rm".

> Sometimes labtainer labs runs into trouble such as work counter not
> increasing, checkwork not showing satisfied result, etc, students want to
> do it from a clean start, so using checkwork showing previous results make
> them confusing.
>
I'll think about adding an option to "check work subsequent to my previous
--redo" so the student can elect to see only results that happen after the
most recent redo.  The default behavior will remain as "check my work as
the instructor will see it, i.e., did I ever achieve the goals?".

> For the --redo command, (correct me if I'm wrong), if a user did something
> else in labtainer using --redo, should it show the corresponding results?
> Otherwise it also may confuse the user; for the original version of
> finished work, From my personal view, user can(should) preserve the
> original output (copy the zip from labtainer_xfer) to somewhere else by
> himself.
>
As noted above, that is not the intent of redo.  But the additional option
should let such students view results subsequent to redo -- though the
instructor will see all results, unless the student deletes from the xfer
directory (which is not encouraged).

> From a brief look at the redo (labutils.py:1973 - RedoLab() and
> StartLab()) python script, current implementation only starts a fresh
> container. Might be better if deletes all previously saved files (or get a
> new command doing this).
>
Again, "redo" is intended to give a fresh lab environment.  It was not and
will not be a means to delete artifacts.

Thanks again for the report.  I'll post again when the update is published.
--Mike

Really appreciated!

**Comment by xigaoli** [comment]
Thanks!

**Comment by mfthomps** [comment]
An update has been published to create a new container for checkwork operations.  Use 
update-labtainer.sh to get the update.

**Comment by xigaoli** [comment]
It worked, thanks a lot!
