### ISSUE TITLE
"Framework installation" tarball not found

### ISSUE THREAD

**Issue by olberger** [mfthomps/Labtainers#15]
https://my.nps.edu/documents/107523850/109121362/labtainer.tar/6fc80410-e87d-4e47-ae24-cbb60c7619fa currently fails : 
```
wget https://my.nps.edu/documents/107523850/109121362/labtainer.tar/6fc80410-e87d-4e47-ae24-cbb60c7619fa
--2019-03-18 08:59:41--  https://my.nps.edu/documents/107523850/109121362/labtainer.tar/6fc80410-e87d-4e47-ae24-cbb60c7619fa
Résolution de my.nps.edu (my.nps.edu)… 205.155.65.19
Connexion à my.nps.edu (my.nps.edu)|205.155.65.19|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2019-03-18 08:59:43 erreur 404 : Not Found.
```

**Comment by mfthomps** [comment]
Broken links to the labtainer.tar and the designer framework installation have been fixed.
Thanks for the report.

**Comment by olberger** [comment]
Uh, IIUC the URLs have changed... which breaks the update-labtainer.sh for existing installations/VMs... ?

**Comment by mfthomps** [comment]
Ug, yes you a correct.  Adding a redirect now.
