### ISSUE TITLE
Add an explicit mention of terms of distribution/use in the README

### ISSUE THREAD

**Issue by olberger** [mfthomps/Labtainers#2]
AFAIU, the code of Labtainers (and some docs) are under public domain, but some labs are under the GFDL.

It would be clearer for users / adopters / contributors to find description of such conditions upfront, in the README (or a LICENSE file, but which is a bit inapropriate maybe for public domain works ;)

**Comment by mfthomps** [comment]
Thanks for the suggestion.  Conditions are now part of the readme.
