### ISSUE TITLE
VirtualBox has depricated 3D acceleration using the VBoxVGA graphics controller

### ISSUE THREAD

**Issue by nathanmuccino** [mfthomps/Labtainers#24]
Starting with VirtualBox 6.1.0, 3D acceleration using the VBoxVGA graphics controller will be deprecated. This could be problem since the currently offered Labtainer OVA image for VirtualBox comes pre-configured for 3D acceleration using the VBoxVGA graphics controller enabled by default. Full error/warning message below:

Console: VM runtime error: fatal=false, errorID=3DCrDeprecated message="This VM is configured to use 3D acceleration using the VBoxVGA graphics controller. Support for this will be removed with version 6.1.0. ALL saved states and snapshots will cease to work when using this configuration. Either switch to the VMSVGA graphics controller and update guest additions, or disable 3D acceleration"

**Comment by mfthomps** [comment]
Thanks for the heads-up.  We'll be building a new VM soon (one that is larger).  I don't see a planned release date for 6.1.0.  Hope they are slower than I am!

**Comment by mfthomps** [comment]
The newly published VM uses the VMSVGA controller.  Thanks again for the report.
