### ISSUE TITLE
pass-crack lab - checkwork

### ISSUE THREAD

**Issue by syndir** [mfthomps/Labtainers#25]
The 'checkwork' command for the pass-crack lab does not seem to count invocations of crackPre.py against the specific files htaccess-sha1 or htaccess-me, but does count the total invocations of crackPre.py against any target.

eg.

```Labname pass-crack

Student              |           chage |        crackSHA |        crackMD5 |        crack512 |        crackPre |   crackPre_sha1 |     crackPre_me |        htpasswd |
==================== | =============== | =============== | =============== | =============== | =============== | =============== | =============== | =============== |
xxxxxxxxxxxxxxxxxxxx |               1 |               2 |               2 |               1 |               3 |               0 |               0 |               6 |
What is automatically assessed for this lab:

	Counts of program invocations
```
maintains 0's in the crackPre_sha1 and crackPre_me columns regardless of executing `./crackPre.py htpasswd-me calc` or `./crackPre.py htpasswd-sha1 calc` as instructed.

**Comment by mfthomps** [comment]
The lab manual says to run the crackPre.py program on htpasswd-me and htpasswd-sha1,
not on "htaccess..."   Our prescribing the file name can lead to this kind of error -- but it does make the automated grading easier.

**Comment by vuxhieues** [comment]
i do exactly as instructed but my crackPre_sha1 and crackPre_me still 0

**Comment by mfthomps** [comment]
That does seem broken.  Do not treat the "check-work" as being perfect, it
is far from that.  The main thing is to explore and learn.
Thanks.

**Comment by mfthomps** [comment]
The version of the openjdk depends on the version of the distribution, which depends on the selected Labtainers container base image.  Labtainers has a network3 base that uses Ubuntu22.  I don't know if that supports jdk22, but it does support 17 and maybe later.  If you need a later ubuntu, see the scripts/designer/basedockerfiles directory and perhaps build your own newer base ubuntu image.
