### ISSUE TITLE
Default Number of Virtual CPUs

### ISSUE THREAD

**Issue by nathanmuccino** [mfthomps/Labtainers#30]
Is there a particular reason why the Labtainer virtual machine images seem to allocate two virtual CPUs by default? I've read and have been told from others who work in the area of virtualization that in most cases allocating more than one virtual CPU to a virtual machine instance can cause significant performance degradation due to the somewhat counter-intuitive way that resource sharing is handled between the host and the virtualized guest OS.

**Comment by mfthomps** [comment]
The allocation of two cpu's was based on observations we made a while back of performance on a set of target laptops.  In any event, that value can be adjusted by the user to reflect their platform.
