### ISSUE TITLE
Student Doc for Nmap-Discovery lab is vague on "friedshrimp.txt" located

### ISSUE THREAD

**Issue by Chad-Ballay** [mfthomps/Labtainers#34]
![image](https://user-images.githubusercontent.com/29847796/75502203-c055be80-5997-11ea-90fb-4b5d3905cd2a.png)

The scenerio doc is vague about where to find this friedshrimp.txt file.  Can additional breadcrumbs be left for the student to find it?

**Comment by mfthomps** [comment]
Thought that was fixed earlier, sorry.  The manual will be updated to tell students, "...your username and password are both 'ubuntu'.  Expect to publish a release this week.
Thanks for the report.

**Comment by Chad-Ballay** [comment]
Ok.  Thank you for creating this.  

If I find anything else as I work through these I'll submit PR's.  Probably should have done that in the first place just because it cuts down on the headache for you.
