### ISSUE TITLE
Ubuntu 20.04 : "python-pip" -> "python3-pip"

### ISSUE THREAD

**Issue by seluard** [mfthomps/Labtainers#37]
Hi,
in Ubuntu 20.04 there is not a python-pip package. Now , you have to install "python3-pip" package.

Best regards! :)

**Comment by mfthomps** [comment]
Hello, thanks for the report!
This is now fixed and will be available in the next release (now in premaster branch).  Also fixed other breakage in the manual install of Labainers.
