### ISSUE TITLE
Labtainer tcpip Error?

### ISSUE THREAD

**Issue by lexirobins** [mfthomps/Labtainers#38]
Attempting the tcpip lab, but I get the following error:

student@ubuntu:~/labtainer/labtainer-student$ labtainer tcpip

[2020-09-22 14:52:29,283 - ERROR : labutils.py:1060 - imageInfo() ] Unable to reach DockerHub.  
Is the network functional?

[2020-09-22 14:52:29,287 - ERROR : labutils.py:1792 - StartLab() ] Could not find image info for server

The other labs seem to work fine and my version of labtainer is up to date. Any recommendations?

**Comment by mfthomps** [comment]
That error suggests a problem reaching the network from the VM.  Are you
able to run a new lab, i.e., one you've never run?
One you run a lab, it no longer needs to hit Docker Hub, so they keep
running even when the network is out.  If you cannot run
new labs, try rebooting the VM.   If you can run new labs, and still only
see that message for the tcpip lab, let me know.
Thanks,
--Mike

**Comment by mfthomps** [comment]
Assuming it was a network failure.
