### ISSUE TITLE
Iptables2 checkwork The wizbang port is not open.

### ISSUE THREAD

**Issue by pedrosa-t** [mfthomps/Labtainers#40]
The checkwork script as some erroneous behavior. 
As the port is random and for some ports the nmap resolves it to a service name instead of unknown that is the expected on results regex. 
Is there a way to specify the check to the expression to matches the WIZ_PORT open instead ?

**Comment by mfthomps** [comment]
Thanks for the report, it is much appreciated.  The next release will include a change to the results.config regex to be:
cw_wizbang_tmp = client:prestop.stdout : FILE_REGEX : ^(?!.*22|80).*.open
Your proposed solution would require a new feature to support parameter substitution within results.config files, which would be nice but a bit of work.  The new release should be out next week.

**Comment by pedrosa-t** [comment]
Your're welcome. Thanks for the fast response and solution.
Congratulations on the Labtainers project and many thanks for the support that you are giving to the community.
