### ISSUE TITLE
lacking a base version, it needs to be retagged with trunk/distrib/retag_all.py

### ISSUE THREAD

**Issue by averydj11** [mfthomps/Labtainers#41]
I can't run any labs without receiving this error, I do the update script and nothing updates. I'm currently running a ubuntu 20.04.2 VM.

**Comment by mfthomps** [comment]
Try this:
cd to the labtainer directory (just above trunk), e.g., cd ~/labtainer
Then:
    wget --quiet https://github.com/mfthomps/Labtainers/releases/latest/download/labtainer.tar -O labtainer.tar
Then 
   cd ../
   tar xf labtainer/labtainer.tar --keep-newer-files --warning=none

Thanks for the report.  Let me know if that does not fix it.

**Comment by mfthomps** [comment]
Turns out the problem was trying to run on the Mac M1 chip.  Labtainers will not run on those new Macs.
