### ISSUE TITLE
Problem on ACL

### ISSUE THREAD

**Issue by nightapm10** [mfthomps/Labtainers#46]
hi,  in the alice_default task
after following the manual step by step but there still isn't a mark when I checkwork
I did : 1. setfacl -d -m user:bob;r-- /alice    for put bob into the default setting
          2. check bob can read new file after 1
          3. setfacl -b /alice for revise
Is there anything wrong?

Also, on task 3, request modify script, but I don't knwo the ascii art either and prof didn't even mention it in the lecture, is that mean I have to learn something about it in a ACL task?

regrads

**Comment by mfthomps** [comment]
Hello,
Your "setfacl" command in (1) is not syntactically correct -- it fails.  Let me know the exact commands and I'll check it out.
You don't need to know anything about ascii art.  You simply need to add commands to the fun script per the manual so that bob gets read access to the file as an effect of alice running the script.

**Comment by nightapm10** [comment]
hi,
thank you for your reply,
actually the (1) should be  setfacl -m d:u:bob:r-- alice

So the before:
![1](https://user-images.githubusercontent.com/38963551/109429001-9cbcbe00-79c7-11eb-9055-1958f9417824.png)

and the after:
![2](https://user-images.githubusercontent.com/38963551/109429005-9fb7ae80-79c7-11eb-928a-d6757e5b1387.png)

I think it's worked, isn't it?  or it's still the wrong one

**Comment by mfthomps** [comment]
The desired policy in the lab manual is:  "As the Alice user, we want to define a default ACL such that, whenever Alice creates a new file in the /shared data/alice directory, that new file will be readable by Bob, but not by users other than Bob
and Alice."

Does your FACL meet all of the requirements of that stated policy?

**Comment by nightapm10** [comment]
seems like I need to read more carefully
thank you for your patient
