### ISSUE TITLE
Labtainer on WSL2

### ISSUE THREAD

**Issue by JM2K69** [mfthomps/Labtainers#51]
Do you plan make available the way to install Labtainer on Windows Subsystem Linux it would be great.

**Comment by JM2K69** [comment]
![image](https://user-images.githubusercontent.com/17923944/122015371-55b0d800-cdc0-11eb-9a2e-3e36506b34a0.png)
![image](https://user-images.githubusercontent.com/17923944/122015469-6b260200-cdc0-11eb-8c70-ea4f12d33a91.png)

Docker is running ;(

**Comment by JM2K69** [comment]
We need to Add 
echo "sudo service docker start" >> ~/.profile for start docker at the launch but the pas is not recognize for labtainer command

**Comment by JM2K69** [comment]
> Do you plan make available the way to install Labtainer on Windows Subsystem Linux it would be great.

For install I need to modify the install-docker ubuntu like this 
## Check if current user is user login. (Targeted to avoid adding root user into docker group instead of the
**Removed** because in WSL2 your aren't log 
```bash
#
# Install Docker on an Ubuntu system, along with other packages required by Labtainers
#

#Check if current user is user login. (Targeted to avoid adding root user into docker group instead of the th>

type sudo >/dev/null 2>&1 || { echo >&2 "Please install sudo.  Aborting."; exit 1; }
sudo -v || { echo >&2 "Please make sure user is sudoer.  Aborting."; exit 1; }
#---needed packages for install
sudo apt-get update
# gdf ubuntu
#sudo apt-get install libcurl3-gnutls=7.47.0-1ubuntu2
````

**Comment by mfthomps** [comment]
Hello,
I've not worked with WSL2.  Other than the VM appliance, the best way to run Labtainers on a Windows system is to use the Docker Desktop.  See the Student Guide for how to install and run Labtainers in that environment.
