### ISSUE TITLE
Student script labutils.py may encounter type conversion error during labtainer startup

### ISSUE THREAD

**Issue by nkremerh** [mfthomps/Labtainers#58]
The labutils.py script may encounter a type conversion error on line 1281 when trying to convert the value of the DISPLAY environment variable to an integer. It may first need to be converted to a float from a string then to an integer, else the following error message is produced:

`ValueError: invalid literal for int() with base 10: '0.0'`

Behavior tested on Arch and Ubuntu.

**Comment by mfthomps** [comment]
See fix for issue #60.
