### ISSUE TITLE
Could not run labedit

### ISSUE THREAD

**Issue by duydthiph** [mfthomps/Labtainers#62]
Hello,

I'm trying to run labedit but I can not get it.
1) First, I run the command "labedit" and I got this message:
student@ubuntu:~/labtainer/labtainer-student$ labedit
Command 'labedit' not found, did you mean:
  command 'ldbedit' from deb ldb-tools
  command 'gabedit' from deb gabedit
Try: sudo apt install <deb name>

2) Second, I followed the instruction, I used the command "./update-designer.sh" and reboot. But when run the command "labedit" again, I got a error as the following:
Error: LinkageError occurred while loading main class labtainers.mainui.MainWindow
java.lang.UnsupportedClassVersionError: labtainers/mainui/MainWindow has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up t o 55.0
Could you pls help me out!

![0](https://user-images.githubusercontent.com/15878822/182659978-c1fa38ff-f431-45b7-8fdb-8c0f80fe894e.png)
![1](https://user-images.githubusercontent.com/15878822/182659990-41950d53-8ab7-43dc-ac0f-9b06ead23a6b.png)
![2](https://user-images.githubusercontent.com/15878822/182659995-2f8cf3f5-e7b2-47d9-974b-a3ebee2ad29c.png)

**Comment by mfthomps** [comment]
The error message indicates the JRE is too old.
Try updating it with:
   sudo apt install default-jre

**Comment by mfthomps** [comment]
... but that should have occurred automatically when you run update-designer.sh.   My guess is update-designer.sh failed, .e.g, due to a network error.  Run update-designer.sh again and watch for errors.
Is this a recent Labtainers VM?

**Comment by duydthiph** [comment]
Yes, it is.
I dowloaded from your website
https://nps.edu/web/c3o/virtual-machine-images
Do you have any idea that can sovle this?

**Comment by mfthomps** [comment]
did you try my suggestion of rerunning update-designer.sh?  As noted earlier, it looks like the JRE was not updated, e.g., 
`sudo atp install default-jre`

**Comment by bobdolectf** [comment]
I'm reflecting the issue same on a fresh vm after rerunning update-designer.sh, have also removed and reinstalled jre.

**Comment by mfthomps** [comment]
I see the problem.  The labedit was rebuilt with a Java environment that is too new.  I need to revert some things and rebuild.  I'll post here when there is a fix.   Sorry about that.

**Comment by mfthomps** [comment]
I posted a fix.  Run update-designer.sh again.  That will install the labedit program compiled with JDK 11.  
And thank you both for the reports.
