### ISSUE TITLE
Problem with gradelab

### ISSUE THREAD

**Issue by duydthiph** [mfthomps/Labtainers#70]
Hello everybody,
I modified lab telnetlab, but I got a problem with gradelab as in the picture. 
Now not only my modified lab but also other labs have the same error.
Could you pls help me out!

![image](https://user-images.githubusercontent.com/15878822/204762793-c32be265-e0e3-486d-b328-f3c6fbbe53ed.png)

**Comment by mfthomps** [comment]
The problem is poor error handling in gradelab.   The gradelab command requires that you provide the name of the lab that you wish to grade, e.g., "gradelab telnetlab".  It should have provided you with a useful error message.   I'll fix that soon.
