### ISSUE TITLE
Wireshark with Docker and Debian11

### ISSUE THREAD

**Issue by bsuarez49** [mfthomps/Labtainers#71]
Hello,
I am using labtainer installed on Debian 11.
I can't seem to use wireshark in lab wireshark-intro for example.
I got this error on launch:
**qt.qpa.xcb: could not connect to display :0
X1
X1024
X1025
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalgl, offscreen, vnc, xcb.**

Thanks for your help

**Comment by bsuarez49** [comment]
@mfthomps thanks for help
### On Debian host : 
**echo $DISPLAY** 
:0

**ls -l /tmp/.X11-unix** 
srwxr-xr-x 1 eleve      eleve      0 17 déc.  08:56 X0
srwxr-xr-x 1 eleve      eleve      0 17 déc.  08:56 X1
srwxr-xr-x 1 Debian-gdm Debian-gdm 0 17 déc.  08:56 X1024
srwxr-xr-x 1 Debian-gdm Debian-gdm 0 17 déc.  08:56 X1025

### On Container host :
**ls -l /var/tmp/.X11-unix**   
srwxr-xr-x 1 ubuntu ubuntu 0 Dec 17 07:56 X0
srwxr-xr-x 1 ubuntu ubuntu 0 Dec 17 07:56 X1
srwxr-xr-x 1    116    125 0 Dec 17 07:56 X1024
srwxr-xr-x 1    116    125 0 Dec 17 07:56 X1025

For information, to launch lab containers without error, I modified the version of cgroup on my Debian host which is by default cgroup2fs by changing the /etc/default/grub file to switch to the cgroups v1 (tmpfs) version:
GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0"

**Comment by bsuarez49** [comment]
It's ok with :
export DISPLAY=unix:0

**Comment by mfthomps** [comment]
I was just about to suggest doing an "echo $DISPLAY" on the wireshark labtainer.   I bet that is a list of displays rather than just the :0.  
Thanks for the report and the information.  I'll fix that bug soon.

**Comment by mfthomps** [comment]
This should now be fixed.
Update Labtainers with update-labtainer.sh
Then remove the old wireshark lab containers with "removelab.spy wireshark"
Then start the lab again.  This bug likely affected all labs having GUI apps.
