### ISSUE TITLE
Running on Apple Silicon Chipset Devices

### ISSUE THREAD

**Issue by kietnaptit** [mfthomps/Labtainers#72]
I have tried to install Labtainers on Ubuntu ARM on VMWare Fusion on Macbook with Apple Silicon Chipset
The installation was successed but the docker image can't run because It was build for x86 platform
Do you have any solution or alternative method for this problem
Thanks

**Comment by mfthomps** [comment]
The Labtainer labs will not run on the M1 chip or other non-x86 platforms.   One alternative is to use a cloud based Labtainer VM as described in the Student Guide docs/student/labtainer-student.pdf.  I would suggest the Google Cloud Platform as described in section 5.2 of the Student Guide.
