### ISSUE TITLE
MACVLAN_EXT option editing from Labedit breaks start.config file

### ISSUE THREAD

**Issue by Blutsh** [mfthomps/Labtainers#73]
### Description
Adding a MACVLAN_EXT from labedit GUI (Networks) breaks the `start.config` file.

A space character is missing between MACVLAN_EXT and the actual number selected from GUI.

### Expected behavior
From labedit, in network settings, when I select `1` in the dropdown MACVLAN_EXT the `start.config` file gets edited and the following line :

```
MACVLAN_EXT 1 
```

Is being written.

### Actual behavior
From labedit, in network settings, when I select `1` in the dropdown MACVLAN_EXT the `start.config` file gets edited and the following line :

```
MACVLAN_EXT1 
```

Is being written.

which causes the build to crash :

```
[2023-03-26 09:03:31,094 - ERROR : ParseStartConfig.py:227 - get_configs() ] Fatal. Missing value for:      MACVLAN_EXT1
 
Please fix your start.config file at line 6
```

### Reproducible example
 1. run labedit
 2. create an new lab
 3. add a network
 4. select 1 in MACVLAN_EXT in the new network created
 5. Run > build  (crashes)
 6. Check labtainer logs

**Comment by mfthomps** [comment]
Fixed in v1.3.7r
