### ISSUE TITLE
Radius Lab checkwork can't solve 'radiusd running'

### ISSUE THREAD

**Issue by TrQ-Hoan** [mfthomps/Labtainers#74]
https://github.com/mfthomps/Labtainers/blob/aaf71c83faba43222fc22e11e1f545c64c255205/labs/radius/instr_config/results.config#L13

In `radius/_bin` not found `prestop` how to get `prestop.stdout`?

https://github.com/mfthomps/Labtainers/blob/f9d04dce7fda45231b09f51f8ccb6daacbd3aac8/scripts/labtainer-student/bin/labutils.py#L2123-L2130

**Comment by mfthomps** [comment]
Thanks for the report. I hope to look into this in a day or two.

**Comment by mfthomps** [comment]
That "result" was intended as a hint to students when running checkwork.  The prestop script seems to have been lost.  I'll add it back into the baseline.  Thanks again for the report.
