### ISSUE TITLE
Support for Ubuntu 22+

### ISSUE THREAD

**Issue by AlexanderDefuria** [mfthomps/Labtainers#84]
With no support for Ubuntu 22 onwards it should be noted for users as Ubuntu being one of the most popular Linux distributions has largely moved to Ubuntu 22 LTS and 23. Support is not necessary but it should be very clear that current versions of Ubuntu are not supported.

**Comment by mfthomps** [comment]
The Labtainers home page was updated to reflect this limitation.  I've not looked at the technical issue for some time, perhaps by now there is a work-around.

**Comment by AlexanderDefuria** [comment]
@mfthomps You'd noted it was a systemd versioning issue iirc. Do you have any other information on it so I could use that as a starting point to look for a work around?

**Comment by mfthomps** [comment]
I cannot recall the specific error, but a google of "docker systemd 248" shows the moby issue #42275 which is related.  I think the only path I saw at the time required rebuilding all of the labs, and I could not confirm if that would even work without a big investment in time.
