### ISSUE TITLE
Unable to open website. `xsite` lab on google cloud

### ISSUE THREAD

**Issue by Dissfall** [mfthomps/Labtainers#91]
Hi! I cannot open website `www.xsslabelgg.com` from lab manual. But if I try to ping straight from attacker terminal, the server is accessible. Seems like a DNS problem.

Also it is not possible to restart Apache server on server machine.

![CleanShot 2024-10-16 at 11 51 42](https://github.com/user-attachments/assets/327a5e40-6cc2-4830-a6c0-7417963a5249)

**Comment by mfthomps** [comment]
Thanks for the report.  The problem is much more fundamental, and breaks all labs that rely on systemd.  I should be able to push a fix tomorrow.  Sorry about the slow reply.
